services:
  - type: web
    name: swing-scribe-dashboard
    env: static
    buildCommand: cd swing-scribe-mainfolder/swing-scribe-dashboard-main && npm install && npm run build
    staticPublishPath: dist